---
apiVersion: v1
kind: Service
metadata:
  namespace: #namespace
  name: #service
spec:
  type: NodePort
  ports:
    - port: 8080?
      targetPort: 4000?
      nodePort: 30097?
  selector:
    run: #service
