---
apiVersion: v1
kind: Service
metadata:
  namespace: #namespace
  name: #service
spec:
  type: NodePort
  ports:
    - port: 8080?
      targetPort: 4000?
      nodePort: 30097?
  selector:
    run: #service
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: #service
  name: #service
spec:
  ports:
  - name: #8080-8080
    port: #8080
    protocol: TCP
    targetPort: #8080
    nodePort: #31200
  selector:
    run: #file-server
  type: NodePort
